---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Name:
    - opsschool-consul*
  instance-state-name: running
hostnames:
  - network-interface.association.public-ip
keyed_groups:
  - prefix: consul_server
    key: tags['consul_server']
  - prefix: consul_agent
    key: tags['consul_agent']

all:
  ec2_region: us-east-1
